### PR TITLE
fix syntax error in AI.js

### PR DESCRIPTION
**Pull request by lasconic**

### CODE REVIEW

**Comment by douglaseck** [comment]
Thanks for the pull request. I just used this fork to test some things out.
Then we moved everything into Magenta (using a pull request from the
original aiexperiments author).  Could you submit your pull request against
this repo?
https://github.com/tensorflow/magenta/tree/master/ai-duet

Thanks!

**Comment by lasconic** [comment]
Fair enough. Thank you for the quick feedback. 
In Magenta I don't see the same error, so no need for this PR.
On the other hand, I don't see a way to use polyphonic model in the AI duet from magenta repo, while this branch does work well once this file is fixed!

**Comment by douglaseck** [comment]
I moved this to an email conversation. Let's figure out a plan there.

**Comment by douglaseck** [comment]
In the meantime I see no reason not to apply this.

**Pull request merged**
